apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfhelper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdfhelper
  template:
    metadata:
      labels:
        app: pdfhelper
    spec:
      containers:
      - image: iramovs/rso-pdfhelper:1.0.0-SNAPSHOT-17.1
        name: pdfhelper
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: cluster-1
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://10.11.245.103:2379
          - name: KUMULUZEE_DISCOVERY_ETCD_USERNAME
            value: root
          - name: KUMULUZEE_DISCOVERY_ETCD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: etcd-pass
                key: ETCD_PASSWORD
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://104.198.64.160:8080
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: pdfhelper
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: pdfhelper
