kumuluzee:
  name: pdfhelper-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  discovery:
    etcd:
      hosts: http://localhost:2379
